---
- name: Configure Artifact Repository
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt: name=nginx state=present update_cache=yes

    - name: Create Artifact Directory
      file:
        path: /var/www/html/artifacts
        state: directory
        mode: "0777"

    - name: Configure Autoindex
      blockinfile:
        path: /etc/nginx/sites-available/default
        insertafter: "server_name _;"
        block: |
          location /artifacts {
            autoindex on;
            client_max_body_size 100M;
          }
      notify: Restart Nginx

    # --- NOWA SEKCJA: Włączenie logowania hasłem ---
    - name: Enable Password Authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication yes"
      notify: Restart SSH
    # -----------------------------------------------

    - name: Set password for vagrant user
      shell: echo "vagrant:vagrant" | chpasswd

  handlers:
    - name: Restart Nginx
      service: name=nginx state=restarted

    - name: Restart SSH
      service: name=ssh state=restarted
