---
- name: Configure Frontend Server (Runtime)
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Clean default html
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent

    # Artefakt (zip) zostanie rozpakowany do /var/www/html przez deploy.sh
    - name: Ensure permission
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    # --- NOWA SEKCJA: FIX SSH ---
    - name: Enable Password Authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication yes"
      notify: Restart SSH

    - name: Set password for vagrant user
      shell: echo "vagrant:vagrant" | chpasswd
    # ----------------------------

  handlers:
    - name: Restart SSH
      service: name=ssh state=restarted
