---
- name: Configure Frontend Server (Runtime)
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt: name=nginx state=present update_cache=yes

    - name: Clean default html
      file: path=/var/www/html/index.nginx-debian.html state=absent

    # Artefakt (zip) zostanie rozpakowany do /var/www/html przez deploy.sh
    - name: Ensure permission
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
